# Generated by Django 3.2.5 on 2021-10-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='full name', max_length=144),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisors',
            field=models.ManyToManyField(blank=True, to='employee_data_app.Supervisor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
