# Generated by Django 3.2.5 on 2021-10-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_app', '0002_rename_supervisor_supervisor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('excel_file', models.FileField(upload_to='excel')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('records_uploaded', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('errors', models.CharField(max_length=100)),
            ],
        ),
    ]
