# Generated by Django 3.2.5 on 2021-10-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_app', '0003_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='errors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='records_uploaded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
