# Generated by Django 3.2.5 on 2021-10-17 19:22

from django.db import migrations, models
import employee_data_app.validator


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_app', '0004_auto_20211017_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='excel_file',
            field=models.FileField(upload_to='excel/%Y/%m/%d', validators=[employee_data_app.validator.validate_file_extension]),
        ),
    ]
