# Generated by Django 3.2.5 on 2021-10-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_app', '0007_alter_supervisor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee_data_app.employee'),
        ),
    ]
