# Generated by Django 3.2.5 on 2021-10-18 18:51

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_app', '0008_alter_supervisor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='excel_file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
